name: Build

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v2
      - name: Setup Build
        run: msbuild .\PhysicsGame.sln /p:Configuration=Release


      - name: Hello World
        run: echo Hello World
      - name: Upload directory
        run: dir

      - name: Create directory
        run: mkdir "artifact/PhysicsGame/"

      - name: Copy directory
        run: copy "dir" "artifact/PhysicsGame/"
        
